### ISSUE TITLE
Palindrome Number

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Programming#10]
## Write a program to check whether a number is palindrome or not.

Maximum number of people can work on this issue there is no limits, make sure that the each filename should also contain your ```username``` to avoid merge conflicts and overriding.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by MSoumen** [comment]
I've solved it. I'll make a PR tomorrow.

**Comment by AKASHCS50** [comment]
I would like to work on this.

**Comment by Ankitkumarjaiswal** [comment]
I have solved this issue in C.

**Comment by janmejai2002** [comment]
I would like to contribute this using Python.

**Comment by roshnaeem** [comment]
Hey @G1Joshi, i want to solve this in Javascript.

**Comment by ayerhs7** [comment]
I have solved this issue using C++. Kindly assign this task to me.

**Comment by mcmonojit** [comment]
Hello @G1Joshi , I would like to work on this issue in Java. Can I contribute to this issue ?

**Comment by 16sweetyjain** [comment]
can i work on this issur using CPP?

**Comment by GC2002** [comment]
Hi! I have a very short and easy code for it in python. Please assign it to me.

**Comment by sagarwala** [comment]
Hi @G1Joshi  , I have added the palindrome number program in golang.
