### ISSUE TITLE
Armstrong Number

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Programming#11]
## Write a program to check whether a number is armstrong or not.

Maximum number of people can work on this issue there is no limits, make sure that the each filename should also contain your ```username``` to avoid merge conflicts and overriding.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by kratikaatgithub** [comment]
Hi I would like to work on this issue as part of hacktoberfest 2020.

**Comment by G1Joshi** [comment]
Sure @kratikaatgithub, all the best 🚀

**Comment by ADshady13** [comment]
Hello, I would like to work on this please.

**Comment by glitches-coder** [comment]
hello i would like to work on this

**Comment by AparnaJuhi** [comment]
@G1Joshi I have done armstrong numbers in python. Please review my PR

**Comment by GC2002** [comment]
hi ! can I work on this?

**Comment by priyalgupta09** [comment]
hey! can i work on this please .
i cn make  a C program
