### ISSUE TITLE
Fibonacci Series upto nth terms

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Programming#12]
## Write a program for fibonacci series upto nth terms.

Maximum number of people can work on this issue there is no limits, make sure that the each filename should also contain your ```username``` to avoid merge conflicts and overriding.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by yashmehta17** [comment]
Hi, I would like to work on this issue.

**Comment by G1Joshi** [comment]
Sure @yashmehta17, you can start working.

**Comment by togami2864** [comment]
Hello. I want to work on this issue by using python.

**Comment by ayerhs7** [comment]
I have solved this issue using C++. Kindly assign this task to me.

**Comment by mfarchana** [comment]
Solve it with php :)

**Comment by GhostUser** [comment]
I've added the Fibonacci series using recursion in python.
#379

**Comment by togami2864** [comment]
I solved this in python. #384
