### ISSUE TITLE
Factorial of a Number

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Programming#13]
## Write a program to find factorial of a number.

Maximum number of people can work on this issue there is no limits, make sure that the each filename should also contain your ```username``` to avoid merge conflicts and overriding.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by ashirbad29** [comment]
I want to contribute :)

**Comment by G1Joshi** [comment]
Sure @ashirbad29, everyone can contribute.

**Comment by DevDaksh** [comment]
I'd like to contribute too, I've worked on a similar issue before

**Comment by codebook-2000** [comment]
#136 Code for Factorial of a no in java

**Comment by athiratj** [comment]
Added c program to find factorial of a number using function. #127
Thanks.

**Comment by navi532** [comment]
I would like to contribue in it in python

**Comment by ayerhs7** [comment]
I have solves this issue using C++. Kindly assign this task to me.

**Comment by debajit13** [comment]
Hi @G1Joshi , I would like to work on this issue in JavaScript

**Comment by GhostUser** [comment]
Added Factorial in python using recursion
#295

**Comment by mafiamamba** [comment]
Hello @G1Josh , I have added the C program for the finding the factorial of a number. :)

**Comment by sagarwala** [comment]
Hi @G1Joshi , I have added the factorial of a number code in golang.

**Comment by isabellabond** [comment]
Hello @G1Joshi I just submitted my pull request for my factorial code #492
