### ISSUE TITLE
Power of a Number

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Programming#14]
## Write a program to find the power of a number.

Maximum number of people can work on this issue there is no limits, make sure that the each filename should also contain your ```username``` to avoid merge conflicts and overriding.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by hrishikesharma** [comment]
Brother, I would like to work on this issue(python).  After solving, Should I put the file in the python folder?  Actually, I'm new here :P

**Comment by debajit13** [comment]
Hi, @G1Joshi , I would like to work on this issue. Can I work on it?

**Comment by ayerhs7** [comment]
I have solves this issue using C++. Kindly assign this task to me.

**Comment by ayerhs7** [comment]
*solved

**Comment by AasthaSinha2305** [comment]
@G1Joshi I have a created a pull request #411  for this issue. I have added the code for finding power of a number. Please can you verify it.
