### ISSUE TITLE
Factors of a Number

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Programming#15]
## Write a program to find the factors of a number.

Maximum number of people can work on this issue there is no limits, make sure that the each filename should also contain your ```username``` to avoid merge conflicts and overriding.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by kratikaatgithub** [comment]
Hi I would like to work on this issue as part of hacktoberfest 2020.

**Comment by G1Joshi** [comment]
Sure @kratikaatgithub, all the best 🚀

**Comment by debajit13** [comment]
Hi, @G1Joshi , I would like to work on this issue as part of hacktoberfest 2020.

**Comment by ayushi-1408** [comment]
Hey! I would like to work on this issue ,if you allow @G1Joshi ?

**Comment by shiv-ani-singh** [comment]
I would like to work on this. Thank you!

**Comment by tiwarikratika** [comment]
can i work on this?
