### ISSUE TITLE
Strong Number

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Programming#16]
## Write a program to check whether a number is strong or not.
A strong number is a number whose sum of factorials of digits is equal to the same number.

Maximum number of people can work on this issue there is no limits, make sure that the each filename should also contain your ```username``` to avoid merge conflicts and overriding.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by Saujanya0910** [comment]
Hey, can I work on this issue as a part of my Hacktoberfest 2020 participation ?

**Comment by mcmonojit** [comment]
Hello @G1Joshi , I would like on this issue.

**Comment by G1Joshi** [comment]
Sure, @Saujanya0910, @mcmonojit you both can work on this issue

**Comment by satwik-chowdary** [comment]
Hey can I do this

**Comment by 16sweetyjain** [comment]
@G1Joshi can i work on this issue since you have mentioned many people can work on it?

**Comment by piyushverma001** [comment]
Hello @G1Joshi  I made a PR at #251 for javascript code Kindly review it.
Cheers!

**Comment by flyingsonu122** [comment]
Hello @G1Joshi I made a PR at #387  for C code Kindly review it.
Cheers!

**Comment by Saujanya0910** [comment]
Hello, @G1Joshi I had made a PR at #79 for C++ code to check for Perfect Number 3 DAYS ago. Please review it and merge it if it is possible. Thanks!
