### ISSUE TITLE
Perfect Number

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Programming#17]
## Write a program to check whether a number is perfect or not.
Perfect number is a positive number which is equal to the sum of all its divisors excluding itself.

Maximum number of people can work on this issue there is no limits, make sure that the each filename should also contain your ```username``` to avoid merge conflicts and overriding.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by Saujanya0910** [comment]
Hey, can I work on this issue as a part of my Hacktoberfest 2020 participation ?

**Comment by GowthamGoush** [comment]
Hello Jishi, I would like to work on this. Shall I ?

**Comment by niki-beep** [comment]
Hey..I want to work on this issue.

**Comment by Nyakinyua** [comment]
Hi, I would like to work on this issue

**Comment by G1Joshi** [comment]
Sure @Saujanya0910, @GowthamGoush, @niki-beep, @Nyakinyua, you can start working on this issue, every valid pull request will be merged.

**Comment by ayushi-get** [comment]
Hi, i would like to work on this issue

**Comment by piyushverma001** [comment]
Hello @G1Joshi  I made a PR at #251 Kindly review it.
Cheers!

**Comment by kaushambisharma** [comment]
Hey,I would like to work on this issue.

**Comment by Saujanya0910** [comment]
Hello, @G1Joshi I had made a PR at #79 for C++ code to check for Perfect Number 3 DAYS ago. Please review it and merge it if it is possible. Thanks!
