### ISSUE TITLE
Positive or Negative Number

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Programming#3]
## Write a program to check whether a number is positive or negative.

Maximum number of people can work on this issue there is no limits, make sure that the each filename should also contain your ```username``` to avoid merge conflicts and overriding.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by Sujal124** [comment]
Please allow me to work on this issue

**Comment by G1Joshi** [comment]
Sure @Sujal124 go for it,
Anyone can work on this issue, this issue is open for all.

**Comment by Ajeet1606** [comment]
@G1Joshi I want to work on it.

**Comment by G1Joshi** [comment]
Sure @Ajeet1606 go for it

**Comment by shreyamodi1999** [comment]
Can I work on this? @G1Joshi

**Comment by Juarsh** [comment]
I would like to work on this

**Comment by codebook-2000** [comment]
#196 Added the code for positive or negative no checking in java

**Comment by kirit01** [comment]
Added the code for positive or negative no checking in Python

**Comment by senbagaraman04** [comment]
#580  added code for positive and negative number
