### ISSUE TITLE
Highest Common Factor

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Programming#30]
## Write a program to find the highest common factor of two numbers.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by harshguptahg007** [comment]
I wanted to work on this issue for my hacktoberfest. Please assign it to me.

**Comment by TheCoderNikhil** [comment]
I wanted to work on this issue for my hacktoberfest. Please assign it to me, can i work on python

**Comment by shrishtrip** [comment]
Hey, can I provide the python implementation?

**Comment by Mayankjha997** [comment]
hey can i provide the c implementation

**Comment by ITES7321** [comment]
Hi! can I work on this issue using cpp? Thanks!
