### ISSUE TITLE
💡 : Find the second largest in a list of numbers

### ISSUE THREAD

**Issue by joe733** [C0D1NG/Programming#324]
**Problem Statement**:
Given a list of size `l`. Find the second largest number in that list. Come up with an effective method / algorithm.

**Example**:
<pre>
list = [23, 51, 12, 19, 8]
2<sup>nd</sup> largest number = 23
</pre>

**Bonus**:
Find the `n`<sup>th</sup> _largest_ or _smallest_ number in a given list.

**Comment by mathewvarghesemanu** [comment]
Added a code snippet based on loops including comments.

**Comment by joe733** [comment]
@mathewvarghesemanu, right here? as a solution?

**Comment by mathewvarghesemanu** [comment]
> @mathewvarghesemanu, right here? as a solution?

No, in-branch #324. I've raised a pull request. Please check, Thanks

**Comment by DhruvSondhi** [comment]
can i contribute to this issue in C++ if it is still open ?

**Comment by joe733** [comment]
@mathewvarghesemanu needs some work: https://github.com/C0D1NG/Programming/pull/389#discussion_r499116835

@DhruvSondhi sure. I'm not a <kbd>contributor</kbd> yet, but I think @C0D1NG won't be displeased though.. :)

**Comment by funwaa** [comment]
Done in bash in #462 including the bonus, can find nth largest or smallest number in a list loaded from file
