### ISSUE TITLE
Binary to Decimal

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Programming#33]
## Write a program to convert binary number into decimal number.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by debajit13** [comment]
Hi @G1Joshi, I would like to work on this issue.

**Comment by krishna16sharma** [comment]
Hi @G1Joshi !
May i work on this issue?

**Comment by aansh-01** [comment]
Can i please do task in c++ language

**Comment by alpceylan** [comment]
I'm taking up this issue

**Comment by krithikha2001** [comment]
Can i also work in this issue

**Comment by VeigaThiago** [comment]
I'll do for javascript

**Comment by akumar-99** [comment]
I am doing it for python.

**Comment by animesh288** [comment]
Hi, i would like to do this in java

**Comment by ralfjayjovenal-cp** [comment]
Hey @G1Joshi. Kindly check PR #284 for PHP. Thanks!

**Comment by akumar-99** [comment]
@CiTRuS93 Please check this PR commit #285 - Upgraded version of your code.
@G1Joshi Please check the PR.

**Comment by abdullah2205** [comment]
Hi, I am beginner, Can I contribute this project?

**Comment by Mayankjha997** [comment]
hey! i can contribute in c language

**Comment by ParanoidWolf** [comment]
Added bash script #452

**Comment by amartya-k** [comment]
Added in ruby [https://github.com/C0D1NG/Programming/pull/510#issue-500929832](pull request)

**Comment by djl218** [comment]
I will add some code for Java

**Comment by jhalak27** [comment]
@G1Joshi I have added code in c++ #592
