### ISSUE TITLE
Decimal to Binary

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Programming#35]
## Write a program to convert decimal number into binary number.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by itsnitinr** [comment]
I've started working on the JavaScript implementation. Will open a PR soon :)

**Comment by debajit13** [comment]
Hi @G1Joshi, I want to work on this issue using C++.

**Comment by CiTRuS93** [comment]
hey can I have this in python?

**Comment by Harshit107** [comment]
Hello, can I solve this problem using java?

**Comment by saumya66** [comment]
I have submitted a PR solving two issues . @G1Joshi

**Comment by saumya66** [comment]
Sure @erikhlp I have just pushed the C++ versions you go on with C

**Comment by shrishtrip** [comment]
Hi @G1Joshi , can I provide the cpp implementation ?

**Comment by VeigaThiago** [comment]
I'll do for javascript

**Comment by sayaPintar** [comment]
can i use c#?

**Comment by animesh288** [comment]
hi, i would like to do this in java

**Comment by mfarchana** [comment]
Solve with PHP

**Comment by SMITVASOYA** [comment]
I want to contribute this issue. So can I?

**Comment by ParanoidWolf** [comment]
Added bash script for decimal to binary conversion #452

**Comment by ParanoidWolf** [comment]
#452

**Comment by djl218** [comment]
I will do one for Java
