### ISSUE TITLE
Maximum Number of Handshakes

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Programming#37]
## Write a program to find the maximum number of handshakes if there are N persons.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by debajit13** [comment]
Hi @G1Joshi , I would like to work on this issue.

**Comment by AbhipsaGuru1012** [comment]
@G1Joshi hi, can I work on this issue using Java?

**Comment by krishna16sharma** [comment]
Hi @G1Joshi !
Can I work on this issue too?

**Comment by bmusuko** [comment]
Can i work in this issue @G1Joshi? I can do it with golang or any other language

**Comment by Kunal0127** [comment]
I would like to work on this issue. can i?

**Comment by mcmonojit** [comment]
Hello @G1Joshi , I would live to work on this issue. The implementation will be in Java.

**Comment by tushar2407** [comment]
Hi @G1Joshi 
while cloning the repo, There is this error coming up:
error: invalid path 'Python/yashaswinipai:decimaltobin.py'
Can you please resolve it? I wish to contribute to this issue.
Thanks

**Comment by tushar2407** [comment]
Hi @G1Joshi,
I wish to contribute to this repo. But am unable to push changes through my created branch.
An error while pushing says:
remote: Permission to C0D1NG/Programming.git denied to tushar2407.
fatal: unable to access 'https://github.com/C0D1NG/Programming.git/': The requested URL returned error: 403

Can you please help with the same.
Thanks

**Comment by tushar2407** [comment]
> Hi @G1Joshi,
> I wish to contribute to this repo. But am unable to push changes through my created branch.
> An error while pushing says:
> remote: Permission to C0D1NG/Programming.git denied to tushar2407.
> fatal: unable to access 'https://github.com/C0D1NG/Programming.git/': The requested URL returned error: 403
> 
> Can you please help with the same.
> Thanks

Sorry and thanks. I found my mistake.

**Comment by Nightsmore** [comment]
#488  I've added a PR for this issue

**Comment by garvitgupta13** [comment]
@G1Joshi I have created a PR #436  . Kindly check it

**Comment by mgncodes** [comment]
@G1Joshi I have added Python code for this problem in PR #516 . Kindly check and approve.
