### ISSUE TITLE
Even or Odd Number

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Programming#4]
## Write a program to check whether a number is even or odd.

Maximum number of people can work on this issue there is no limits, make sure that the each filename should also contain your ```username``` to avoid merge conflicts and overriding.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by bhakti0302** [comment]
I would like to work on this.

**Comment by Abhicoder03** [comment]
I want to work on this.

**Comment by G1Joshi** [comment]
Any one can work on any issue...

**Comment by Ajeet1606** [comment]
@G1Joshi How can I work on this. 
Please guide a bit.

**Comment by G1Joshi** [comment]
@Ajeet1606 write a program in your favourite programming language to check whether a given number is even or odd, after writing the program make sure that the filename should contain your username and create a pull request.

**Comment by Ajeet1606** [comment]
> @Ajeet1606 write a program in your favourite programming language to check whether a given number is even or odd, after writing the program make sure that the filename should contain your username and create a pull request.

@G1Joshi Thanks

**Comment by codebook-2000** [comment]
#92 Code for Even-Odd in java

**Comment by roshnaeem** [comment]
Hey @G1Joshi, i want to code it in javaScript.

**Comment by roshnaeem** [comment]
@G1Joshi , kindly review my PR https://github.com/C0D1NG/Programming/pull/195

**Comment by kirit01** [comment]
i want to code it in Python

**Comment by ashirbad29** [comment]
want to contribute in c++

**Comment by ashirbad29** [comment]
I have a small doubt regarding the contribution
first, I created my branch then i solve the  problem in that branch
now should in merge it into the master
if not then how to make the pr

**Comment by Lakshita2002** [comment]
@G1Joshi please check PR #497 Thanks!

**Comment by senbagaraman04** [comment]
Added code in C# , PR #582
