### ISSUE TITLE
Sum of First N Natural Numbers

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Programming#5]
## Write a program to find sum of first N natural numbers.

Maximum number of people can work on this issue there is no limits, make sure that the each filename should also contain your ```username``` to avoid merge conflicts and overriding.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by bhakti0302** [comment]
I would like to work on this.

**Comment by mephi007** [comment]
Hey @G1Joshi I would like to work on this, can you please assign this to me?

**Comment by Sujal124** [comment]
Please assign this to me, I would love to work on this

**Comment by G1Joshi** [comment]
Sure @mephi007 and @Sujal124 you both can work on this issue.
This issue is open for all, I'm not going to assign it individually.

**Comment by codebook-2000** [comment]
#133 Sum of Natural Nos code in java

**Comment by akshat12000** [comment]
Please assign me this issue

**Comment by akshat12000** [comment]
[akshat12000_Sum_Of_FirstN.cpp.txt](https://github.com/C0D1NG/Programming/files/5309493/akshat12000_Sum_Of_FirstN.cpp.txt)

**Comment by akshat12000** [comment]
[https://github.com/akshat12000/animated-telegram/blob/master/akshat12000_Sum_Of_firstN.cpp](url)

**Comment by Aman-Jamshed** [comment]
Hey @G1Joshi  Kindly Check My PR #260 .Please merge my PR as this is my first HACKTOBERFEST!

**Comment by paras399979** [comment]
Hey! Please review my pull request number #455 coded in C++

**Comment by senbagaraman04** [comment]
Added sum of N natural numbers PR  #585
