### ISSUE TITLE
Case sensitive files on a case insensitive filesystem

### ISSUE THREAD

**Issue by kennethpdev** [C0D1NG/Programming#529]
I tried cloning this project but then there are files that have the same name. This works on case sensitive systems. But on Windows its case insensitive, so `A` and `a` is the same. Now there are files that I'm having problem with.

```
Java/BinaryToDecimal_nishiki97.java
Java/binaryToDecimal_nishiki97.java 

Python/Levenshtein_Distance.py
Python/levenshtein_distance.py
```

can the author or this or the maintainer remove these files or at least rename them?

For now I can contribute via the github web. Hoping this would be fix soon.

**Comment by kenma9123** [comment]
can you please take a look at this @G1Joshi

**Comment by bordaj** [comment]
I tried , and came up with a solution . Hoping to discuss more about this .
