### ISSUE TITLE
Largest Element in the Array

### ISSUE THREAD

**Issue by bhavesh1129** [C0D1NG/Programming#66]
**I had added in C++ of Largest Element in the Array.**

**Comment by bnrosa** [comment]
I will do it in php

**Comment by mcmonojit** [comment]
I would like to solve this problem in Java.

**Comment by ashirbad29** [comment]
I can code this up in javascript

**Comment by akumar-99** [comment]
I will code it in python.

**Comment by akumar-99** [comment]
@bhavesh1129 Please check #292

**Comment by BabesGotByte** [comment]
@bhavesh1129 Please check #369 written in C++.
