### ISSUE TITLE
Prime Number

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Programming#7]
## Write a program to check whether a number is prime or not.

Maximum number of people can work on this issue there is no limits, make sure that the each filename should also contain your ```username``` to avoid merge conflicts and overriding.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by 4Rebin** [comment]
Hey, I would like to work with that

**Comment by mephi007** [comment]
Hey @G1Joshi  I would like work on this, can you please assign this to me?

**Comment by G1Joshi** [comment]
Sure @4Rebin and @mephi007 you both can work on this issue, if both issues are valid then I will merge them.

**Comment by codebook-2000** [comment]
#198 Prime Number solved in Java

**Comment by Saharatt593** [comment]
I update future Check whether a number is prime or not with kotlin language.
@G1Joshi  Please check PR. 👍

**Comment by Diegoslourenco** [comment]
@G1Joshi could tou check the PR #402 ?

**Comment by garvitgupta13** [comment]
@G1Joshi please check PR #430. I have added a file

**Comment by Lakshita2002** [comment]
@G1Joshi please check PR #496 Thanks!
