### ISSUE TITLE
Sum of Digits of a Number

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Programming#8]
## Write a program to find sum of digits of a number.

Maximum number of people can work on this issue there is no limits, make sure that the each filename should also contain your ```username``` to avoid merge conflicts and overriding.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by MSoumen** [comment]
I want to work on this using Python.

**Comment by GowthamGoush** [comment]
I would like to work on this

**Comment by G1Joshi** [comment]
Sure @MSoumen and @GowthamGoush you can work on this issue, so start working now.

**Comment by ayushgaur03** [comment]
I would like to wor on this program using Java

**Comment by sagrawal9689** [comment]
I would like to work on this program using c++

**Comment by codebook-2000** [comment]
#118 Sum of Digits code in java

**Comment by ayushgaur03** [comment]
@G1Joshi should i commit my code in Active branch??

**Comment by ralfjayjovenal-cp** [comment]
Hi @G1Joshi  I created PR #293 for PHP. Kindly check. Thanks!

**Comment by garvitgupta13** [comment]
@G1Joshi I have created a PR #435 . Kindly check it

**Comment by mgncodes** [comment]
@G1Joshi Kindly check and approve PR #505 .
