### ISSUE TITLE
Reverse of a Number

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Programming#9]
## Write a program to reverse a number.

Maximum number of people can work on this issue there is no limits, make sure that the each filename should also contain your ```username``` to avoid merge conflicts and overriding.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by MSoumen** [comment]
I've done this . I'll send my PR tomorrow .

**Comment by GowthamGoush** [comment]
Is there any constrain in the input (integer/long) ?

**Comment by G1Joshi** [comment]
Okay @MSoumen 
No @GowthamGoush

**Comment by codebook-2000** [comment]
#150 Code for Reverse of a No in Java

**Comment by stuti-v4** [comment]
Code For Reversing a number
[Reverse of a no.txt](https://github.com/C0D1NG/Programming/files/5307875/Reverse.of.a.no.txt)

**Comment by glitches-coder** [comment]
[](https://github.com/C0D1NG/Programming/pull/327)

**Comment by aniksaha12** [comment]
Hi @G1Joshi , I would like to contribute in this issue

**Comment by AasthaSinha2305** [comment]
@G1Joshi  I have a created a pull request #410 for this issue. Please can you verify it.

**Comment by ramkshukla** [comment]
hi @G1Joshi , i would like contribute this program in python. Can i?

**Comment by priyalgupta09** [comment]
hey! can i work on this
